server:
  port: ${AS_PORT:8080}

spring:
  application:
    name: AuthService
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    properties:
      hibernate:
        format_sql: true
        allow_update_outside_transaction: false
    hibernate:
      ddl-auto: validate
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
      base-path: /actuator
  server:
    port: ${AS_METRICS_PORT:8091}
  endpoint:
    prometheus:
      enabled: true
    health:
      probes:
        enabled: true
      show-details: always
      group:
        readiness:
          include: db, diskSpace, ping
  metrics:
    export:
      prometheus:
        enabled: true