server:
  port: ${KS_PORT:8081}

spring:
  application:
    name: KeyService
  datasource:
    url: jdbc:postgresql://postgres:5433/KeyService
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    properties:
      hibernate:
        format_sql: true
        allow_update_outside_transaction: false
    hibernate:
      ddl-auto: validate
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
      base-path: /actuator
  server:
    port: ${KS_METRICS_PORT:8092}
  endpoint:
    prometheus:
      enabled: true
    health:
      probes:
        enabled: true
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true