server:
  port: 8080

spring:
  application:
    name: AuthService
  datasource:
    url: jdbc:postgresql://postgres:5432/AuthService
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    properties:
      hibernate:
        format_sql: true
        allow_update_outside_transaction: false
    hibernate:
      ddl-auto: update
    show-sql: true