apiVersion: v1
kind: ConfigMap
metadata:
  name: vmagent-promscrape-config
  namespace: monitoring
data:
  promscrape.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
    - job_name: 'BetterProductivity'
      static_configs:
      - targets: []